"""add TelegramAlert table

Revision ID: 777158012961
Revises: 44efa297005a
Create Date: 2023-02-02 14:32:11.434515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '777158012961'
down_revision = '44efa297005a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_alert',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('api_url', sa.String(), nullable=True),
    sa.Column('api_chat', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telegram_alert')
    # ### end Alembic commands ###
