"""add wallet model

Revision ID: d052a45f9309
Revises: 24c2cc9f13ba
Create Date: 2024-06-29 09:27:27.901039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd052a45f9309'
down_revision = '24c2cc9f13ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wallet_id', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_asset_wallet', 'wallet', ['wallet_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_constraint('fk_asset_wallet', type_='foreignkey')
        batch_op.drop_column('wallet_id')

    # ### end Alembic commands ###
